# Test config for CardDown
[deck]
name = "ConfigTest"
tag = ""
start_tag = ""
seperator = ""
save_path = ""
card_path = ""

[parser]
type = "simple"
cardBegin = ""
cardFlip = ""
cardEnd = ""

[media]
path = ""

[obsidian]
noteLinkColor = ""
